# Generated by Django 4.0.2 on 2022-02-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=400, verbose_name='Product Name')),
                ('Catrgory', models.CharField(max_length=200)),
                ('PRDDesc', models.TextField(verbose_name='Product Description')),
                ('PRDPrice', models.DecimalField(decimal_places=4, max_digits=12)),
                ('PRDCost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('PRDCreated', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
