# Generated by Django 3.1.5 on 2022-02-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220221_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Discount Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
