# Generated by Django 4.0.2 on 2022-03-18 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDModel',
            field=models.CharField(default=django.utils.timezone.now, max_length=400, verbose_name='Product Model'),
            preserve_default=False,
        ),
    ]
