# Generated by Django 4.0.2 on 2022-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_prdmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(default='test', upload_to='productimage/', verbose_name='Prduct Image'),
        ),
    ]
