# Generated by Django 4.0.2 on 2022-03-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_prdimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRDImage',
        ),
    ]
