# Generated by Django 4.0.2 on 2022-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(default='', upload_to='productimage/', verbose_name='Prduct Image'),
            preserve_default=False,
        ),
    ]
