# Generated by Django 4.0.2 on 2022-03-21 04:35

from time import timezone
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_alter_brand_id_alter_variant_id'),
        ('product', '0025_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='User Nme'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product_REV',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.product', verbose_name='Product Reviews'),
            preserve_default=False,
        ),
    ]
