# Generated by Django 4.0.2 on 2022-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='unlikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDModel',
            field=models.CharField(max_length=400, verbose_name=' Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDName',
            field=models.CharField(max_length=400, verbose_name=' Name'),
        ),
    ]
