# Generated by Django 4.0.2 on 2022-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_review_likes_review_rate_review_unlikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Image'),
        ),
    ]
