# Generated by Django 4.0.2 on 2022-04-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_style_product_prdstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATSlug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='category url'),
        ),
    ]
