# Generated by Django 4.0.2 on 2022-04-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_category_catslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CATSlug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
