# Generated by Django 4.0.2 on 2022-04-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_category_catprouduct_alter_review_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CATProuduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDCatrgory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category', verbose_name='Category'),
        ),
    ]
