# Generated by Django 3.1.5 on 2022-02-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
