# Generated by Django 4.0.2 on 2022-03-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
